name: company_inventory
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_ui_auth: ^1.10.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  connectivity: ^3.0.6
  flutter_device_type: ^0.4.0
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+4
  provider: ^6.0.3
  seafarer: ^0.1.1
  theme_provider: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  mobx_codegen: ^2.0.7
  

flutter:
  uses-material-design: true
